version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ecom
    ports:
      - "5437:5432"

  redis:
    image: redis:5-alpine
    ports:
      - "6377:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5567:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_VHOST=myvhost

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
      - redis
      - rabbitmq
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./src:/app/src
    command: bash -c "poetry run uvicorn auth.interface.api.main:app --app-dir /app/src --host 0.0.0.0 --port 8000 --log-level debug"
    ports:
      - "8030:8000"
    env_file:
      - .env